### ISSUE TITLE
Could not run jest unit testcases on updating redux-persis-transform-encrypt package version from "3.0.1"to "5.0.0"

### ISSUE THREAD

**Issue by Shubhakarini-Balu** [maxdeviant/redux-persist-transform-encrypt#74]
**It throws below error on running unit testcases**

#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 174895934
#
#
#
#FailureMessage Object: 0000000CB33FB7B0
 1: 00007FF79A1807BF node_api_throw_syntax_error+175823
 2: 00007FF79A09630F v8::CTypeInfoBuilder<void>::Build+12559
 3: 00007FF79AF52AB2 V8_Fatal+162
 4: 00007FF79AA4DD15 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray+101
 5: 00007FF79A8D3253 v8::internal::FeedbackNexus::ic_state+65795
 6: 00007FF79A8F1DD0 v8::debug::Script::GetIsolate+15600
 7: 00007FF79A73DEA0 v8::internal::CompilationCache::IsEnabledScriptAndEval+25952
 8: 00007FF79AC4B1F1 v8::internal::SetupIsolateDelegate::SetupHeap+558193
 9: 00007FF71B011B90

**Comment by maxdeviant** [comment]
This wouldn't explain the internal Node error, but note that as of `v5.0.0` the package is ESM only: https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.0.0

Jest needs to be configured to use its (experimental) support for ESM: https://jestjs.io/docs/ecmascript-modules

**Comment by aleksandr-sidorov** [comment]
I have a similar issue - Jest throws `Cannot find module 'redux-persist-transform-encrypt' from '...'` .
@maxdeviant I've checked the `[ecmascript-modules](https://jestjs.io/docs/ecmascript-modules)` documet that you provided and I found an issue. There is no `"exports": "lib/index.js",` included in the `package.json` of the v5 release.
I've added this line manually right in the `node_modules/redux-persist-transform-encrypt` and Jest was able to transpile it correctly.
Looking forward to v.5.0.2 of your nice library :)

**Comment by maxdeviant** [comment]
> I have a similar issue - Jest throws `Cannot find module 'redux-persist-transform-encrypt' from '...'` . @maxdeviant I've checked the `ecmascript-modules` documet that you provided and I found an issue. There is no `"exports": "lib/index.js",` included in the `package.json` of the v5 release. I've added this line manually right in the `node_modules/redux-persist-transform-encrypt` and Jest was able to transpile it correctly. Looking forward to v.5.0.2 of your nice library :)

This issue should be resolved in [v5.1.0](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.1.0). Please let me know if that version solves your issue.

**Comment by thanhloc-17** [comment]
> > I have a similar issue - Jest throws `Cannot find module 'redux-persist-transform-encrypt' from '...'` . @maxdeviant I've checked the `ecmascript-modules` documet that you provided and I found an issue. There is no `"exports": "lib/index.js",` included in the `package.json` of the v5 release. I've added this line manually right in the `node_modules/redux-persist-transform-encrypt` and Jest was able to transpile it correctly. Looking forward to v.5.0.2 of your nice library :)
> 
> This issue should be resolved in [v5.1.0](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.1.0). Please let me know if that version solves your issue.

I upgraded to 5.1.0, but I still receive the errors **Cannot find module 'redux-persist-transform-encrypt' or its corresponding type declarations.ts(2307)**

<img width="1197" alt="image" src="https://github.com/maxdeviant/redux-persist-transform-encrypt/assets/20339875/4e06aac2-f63a-4569-af72-be9acc79fbdb">

There's my tsconfig.json:
```
"target": "ESNext",
    "module": "esnext",
    "moduleResolution": "node",
```
